services:
  discord-bot:
    build: .
    container_name: dc-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      # 其他配置项使用 config.py 中的默认值，无需在此设置
    volumes:
      # 持久化数据目录
      - ./data:/app/data
      # 持久化日志目录
      - ./data/logs:/app/data/logs
    networks:
      - bot-network
    # 日志配置
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  bot-network:
    driver: bridge

volumes:
  bot-data:
    driver: local
